"""Schema SQLite versionado da telemetria do Jarvis V3."""

DDL = """
PRAGMA foreign_keys=ON;
CREATE TABLE IF NOT EXISTS runs(run_id TEXT PRIMARY KEY,task_id TEXT NOT NULL,started_at TEXT NOT NULL,finished_at TEXT,duration_ms INTEGER NOT NULL,status TEXT NOT NULL,complexity TEXT NOT NULL,risk_class TEXT NOT NULL,operational_mode TEXT NOT NULL,reasoning_class TEXT NOT NULL,jarvis_version TEXT NOT NULL,policy_version TEXT NOT NULL,contracts_version TEXT NOT NULL,config_hash TEXT NOT NULL,budget_limit INTEGER NOT NULL,budget_used INTEGER NOT NULL,budget_override INTEGER NOT NULL,budget_override_reason TEXT,agent_invocation_count INTEGER NOT NULL,unique_agent_count INTEGER NOT NULL,rework_cycles INTEGER NOT NULL,stop_count INTEGER NOT NULL,first_pass_success INTEGER,human_gate_pass_on_first_attempt INTEGER,routing_outcome TEXT NOT NULL,input_tokens INTEGER NOT NULL,cached_input_tokens INTEGER NOT NULL,output_tokens INTEGER NOT NULL,credits REAL NOT NULL);
CREATE TABLE IF NOT EXISTS agent_invocations(invocation_id TEXT PRIMARY KEY,run_id TEXT NOT NULL REFERENCES runs(run_id),agent TEXT NOT NULL,stage TEXT NOT NULL,team TEXT,status TEXT NOT NULL,started_at TEXT NOT NULL,finished_at TEXT,duration_ms INTEGER NOT NULL DEFAULT 0,model TEXT NOT NULL,reasoning_effort TEXT NOT NULL,input_tokens INTEGER NOT NULL DEFAULT 0,cached_input_tokens INTEGER NOT NULL DEFAULT 0,output_tokens INTEGER NOT NULL DEFAULT 0,credits REAL NOT NULL DEFAULT 0,agent_result TEXT,findings_count INTEGER NOT NULL DEFAULT 0,critical_findings_count INTEGER NOT NULL DEFAULT 0,parallel_batch TEXT,blocker TEXT,model_requested TEXT,model_effective TEXT,context_budget TEXT,progress_event TEXT,reasoning_effort_effective TEXT);
CREATE TABLE IF NOT EXISTS transitions(transition_id INTEGER PRIMARY KEY AUTOINCREMENT,run_id TEXT NOT NULL REFERENCES runs(run_id),source TEXT,target TEXT NOT NULL,at TEXT NOT NULL,reason TEXT NOT NULL,stop_reason TEXT,rework_origin TEXT,rework_reason TEXT);
CREATE TABLE IF NOT EXISTS handoffs(handoff_id TEXT PRIMARY KEY,run_id TEXT NOT NULL REFERENCES runs(run_id),stage TEXT NOT NULL,created_at TEXT NOT NULL,output_path TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS findings(finding_id TEXT PRIMARY KEY,run_id TEXT NOT NULL REFERENCES runs(run_id),invocation_id TEXT NOT NULL REFERENCES agent_invocations,category TEXT NOT NULL,severity TEXT NOT NULL,actioned INTEGER NOT NULL,evidence_ref TEXT,created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS human_gates(gate_id TEXT PRIMARY KEY,run_id TEXT NOT NULL REFERENCES runs(run_id),attempt INTEGER NOT NULL,decision TEXT NOT NULL,reason_code TEXT NOT NULL,reason_detail TEXT,at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS decisions(decision_id TEXT PRIMARY KEY,run_id TEXT NOT NULL REFERENCES runs(run_id),agent TEXT NOT NULL,category TEXT NOT NULL,decision TEXT NOT NULL,evidence_refs TEXT NOT NULL,confidence TEXT NOT NULL,confirmed_by TEXT,challenged_by TEXT,overridden_by TEXT,created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS routing_snapshots(routing_id TEXT PRIMARY KEY,run_id TEXT NOT NULL REFERENCES runs(run_id),agents_planned TEXT NOT NULL,agents_invoked TEXT NOT NULL,agents_skipped TEXT NOT NULL,agents_rejected_by_budget TEXT NOT NULL,parallel_batches INTEGER NOT NULL,routing_outcome TEXT NOT NULL,unnecessary_agents TEXT NOT NULL,missing_agents TEXT NOT NULL,created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS release_evals(eval_id TEXT PRIMARY KEY,jarvis_version TEXT NOT NULL,config_hash TEXT NOT NULL,evaluated_at TEXT NOT NULL,routing_score REAL NOT NULL,over_routing_score REAL NOT NULL,under_routing_score REAL NOT NULL,sequence_score REAL NOT NULL,source_ref TEXT);
CREATE TABLE IF NOT EXISTS execution_attempts(execution_id TEXT PRIMARY KEY,run_id TEXT NOT NULL REFERENCES runs(run_id),task_id TEXT NOT NULL,parent_execution_id TEXT,agent_type TEXT NOT NULL,task_type TEXT NOT NULL,policy_version TEXT NOT NULL,attempt_number INTEGER NOT NULL,initial_reasoning TEXT NOT NULL,effective_reasoning TEXT NOT NULL,complexity_score REAL NOT NULL,ambiguity_score REAL NOT NULL,escalated INTEGER NOT NULL,escalation_reason TEXT,input_tokens INTEGER NOT NULL DEFAULT 0,cached_input_tokens INTEGER NOT NULL DEFAULT 0,output_tokens INTEGER NOT NULL DEFAULT 0,total_tokens INTEGER NOT NULL DEFAULT 0,credits REAL NOT NULL DEFAULT 0,duration_ms INTEGER NOT NULL DEFAULT 0,files_read INTEGER NOT NULL DEFAULT 0,files_changed INTEGER NOT NULL DEFAULT 0,tool_calls INTEGER NOT NULL DEFAULT 0,tests_run INTEGER NOT NULL DEFAULT 0,tests_passed INTEGER NOT NULL DEFAULT 0,tests_failed INTEGER NOT NULL DEFAULT 0,review_findings INTEGER NOT NULL DEFAULT 0,success INTEGER,termination_reason TEXT,child_depth INTEGER NOT NULL DEFAULT 0,created_at TEXT NOT NULL,finished_at TEXT,model_requested TEXT,model_effective TEXT,context_budget TEXT,progress_event TEXT,reasoning_effort_effective TEXT);
CREATE TABLE IF NOT EXISTS technical_handoffs(handoff_id TEXT PRIMARY KEY,task_id TEXT NOT NULL,run_id TEXT NOT NULL REFERENCES runs(run_id),execution_id TEXT,classification TEXT NOT NULL,summary TEXT NOT NULL,previous_behavior TEXT NOT NULL,new_behavior TEXT NOT NULL,reading_map_json TEXT NOT NULL,decisions_json TEXT NOT NULL,risks_json TEXT NOT NULL,test_evidence_json TEXT NOT NULL,output_path TEXT NOT NULL,created_at TEXT NOT NULL,policy_version TEXT NOT NULL,evidence_status TEXT NOT NULL,handoff_tokens INTEGER NOT NULL DEFAULT 0,handoff_duration_ms INTEGER NOT NULL DEFAULT 0,teachback_required INTEGER NOT NULL DEFAULT 0,teachback_questions INTEGER NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS teachback_evaluations(evaluation_id TEXT PRIMARY KEY,handoff_id TEXT NOT NULL REFERENCES technical_handoffs(handoff_id),task_id TEXT NOT NULL,question_id TEXT NOT NULL,result TEXT NOT NULL,matched_concepts INTEGER NOT NULL,total_concepts INTEGER NOT NULL,duration_ms INTEGER NOT NULL DEFAULT 0,developer_requested_deeper_explanation INTEGER NOT NULL DEFAULT 0,created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS rag_queries(query_id TEXT PRIMARY KEY,run_id TEXT NOT NULL REFERENCES runs(run_id),team TEXT,query_hash TEXT NOT NULL,retrieval_mode TEXT NOT NULL,context_budget TEXT NOT NULL,candidates INTEGER NOT NULL,selected INTEGER NOT NULL,estimated_tokens INTEGER NOT NULL,latency_ms INTEGER NOT NULL,cache_hit INTEGER NOT NULL,created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS rag_hits(query_id TEXT NOT NULL REFERENCES rag_queries,chunk_id TEXT NOT NULL,repo TEXT NOT NULL,path TEXT NOT NULL,symbol TEXT,content_hash TEXT NOT NULL,lexical_score REAL NOT NULL,semantic_score REAL NOT NULL,final_score REAL NOT NULL,rank INTEGER NOT NULL,PRIMARY KEY(query_id,chunk_id));
"""
