import type { DashboardSummary, Project, RunEvent } from '../../types/api';
import { Link } from 'react-router-dom';

type Props = { project?: Project; summary?: DashboardSummary; loading?: boolean; runId?: string; taskId?: string; events?: RunEvent[] };

export function ContextPanel({ project, summary, loading, runId, taskId, events = [] }: Props) {
  const metrics = [[summary?.total_runs ?? '—', 'Execuções'], [summary?.successful_runs ?? '—', 'Sucesso'], [summary ? summary.average_agent_invocations.toFixed(1) : '—', 'Agents / execução']];
  const status = events.length ? events[events.length - 1].status || events[events.length - 1].event : 'Aguardando tarefa';
  return <aside className="h-max rounded-2xl border border-slate-200 bg-white p-5 shadow-panel"><div className="mb-5 flex justify-between font-extrabold text-slate-900"><span>Contexto</span><span className="text-[11px] font-semibold text-emerald-500">● ao vivo</span></div><div className="grid gap-1.5 border-t border-slate-100 py-4"><small className="text-[10px] font-extrabold tracking-wider text-slate-400">TAREFA ATIVA</small><strong className="truncate text-sm font-semibold tracking-tight text-slate-900">{taskId || (runId ? 'Tarefa em execução' : 'Nenhuma tarefa selecionada')}</strong><span className="text-xs leading-5 text-slate-500">{runId ? `Run ${runId} · ${status}` : 'Crie uma tarefa pelo AGHUse Assistant para começar.'}</span>{runId && <Link className="mt-2 text-xs font-bold text-blue-600 hover:text-blue-700" to={`/tasks/${encodeURIComponent(runId)}`}>Abrir detalhe da execução →</Link>}</div><div className="grid gap-1.5 border-t border-slate-100 py-4"><small className="text-[10px] font-extrabold tracking-wider text-slate-400">PROJETO</small><strong className="text-sm font-semibold tracking-tight text-slate-900">{project?.name || '—'}</strong><span className="text-xs leading-5 text-slate-500">Branch: {project?.default_branch || '—'}</span></div><div className="grid grid-cols-3 gap-2 border-t border-slate-100 py-4">{metrics.map(([value, label]) => <div className="rounded-xl bg-slate-50 p-2 text-center" key={String(label)}><b className="block text-lg text-slate-900">{loading ? '…' : value}</b><span className="text-[10px] text-slate-400">{label}</span></div>)}</div></aside>;
}
