import type { Operation, OperationProposal } from '../../types/api';

type Props = { operations: Operation[]; selected?: Operation; parameters: Record<string, string>; proposal?: OperationProposal; pending?: boolean; error?: string; onSelect: (operation: Operation) => void; onChange: (key: string, value: string) => void; onPreview: () => void; onExecute: () => void };

export function OperationWorkspace({ operations, selected, parameters, proposal, pending, error, onSelect, onChange, onPreview, onExecute }: Props) {
  return <section className="mb-5 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm" aria-labelledby="operation-title">
    <div className="flex flex-wrap items-start justify-between gap-3"><div><span className="text-[10px] font-bold tracking-widest text-violet-500">OPERAÇÕES DO WORKSPACE</span><h2 id="operation-title" className="mt-1 text-lg font-bold text-slate-900">O que você quer fazer?</h2><p className="text-sm text-slate-500">Escolha uma operação guiada; o prompt base permanece protegido.</p></div>{proposal && <span className="rounded-full bg-amber-50 px-3 py-1 text-xs font-bold text-amber-700">{proposal.status}</span>}</div>
    <div className="mt-4 grid gap-2 sm:grid-cols-2 lg:grid-cols-4">{operations.map((operation) => <button type="button" key={operation.operation_id} onClick={() => onSelect(operation)} className={`rounded-xl border p-3 text-left transition ${selected?.operation_id === operation.operation_id ? 'border-violet-400 bg-violet-50' : 'border-slate-200 hover:border-blue-300'}`}><strong className="block text-sm text-slate-900">{operation.name}</strong><span className="mt-1 block text-xs leading-5 text-slate-500">{operation.description}</span>{operation.mutates && <small className="mt-2 block font-bold text-amber-600">Exige aprovação</small>}</button>)}</div>
    {selected && !proposal && <div className="mt-4 grid gap-3 border-t border-slate-100 pt-4"><label className="text-xs font-bold text-slate-600">Objetivo<textarea required value={parameters.objective || ''} onChange={(event) => onChange('objective', event.target.value)} className="mt-1 min-h-20 w-full rounded-lg border border-slate-200 p-2 text-sm outline-none focus:ring-2 focus:ring-violet-400" placeholder="Descreva o que deve ser analisado ou executado" /></label>{selected.operation_id === 'IMPLEMENT' && <label className="text-xs font-bold text-slate-600">Critérios de aceite<textarea value={parameters.acceptance_criteria || ''} onChange={(event) => onChange('acceptance_criteria', event.target.value)} className="mt-1 min-h-16 w-full rounded-lg border border-slate-200 p-2 text-sm outline-none focus:ring-2 focus:ring-violet-400" placeholder="Como saberemos que está concluído?" /></label>}<button type="button" disabled={pending || !parameters.objective?.trim()} onClick={onPreview} className="w-max rounded-lg bg-violet-600 px-4 py-2 text-sm font-bold text-white hover:bg-violet-700 disabled:opacity-50">{pending ? 'Gerando proposta…' : 'Gerar proposta'}</button></div>}
    {proposal && <div className="mt-4 grid gap-3 border-t border-slate-100 pt-4"><div className="grid gap-2 text-xs text-slate-600 sm:grid-cols-2"><div><b>Modelo</b><br />{proposal.model_effective || proposal.model_requested || 'UNKNOWN'}</div><div><b>Reasoning</b><br />{proposal.reasoning || 'UNKNOWN'}</div></div><div className="rounded-lg bg-slate-50 p-3 text-xs text-slate-600"><b>Objetivo:</b> {proposal.parameters.objective}<br /><b>Prompt completo:</b> protegido; apenas hash da proposta é persistido.</div>{proposal.response && <div className="rounded-xl border border-emerald-100 bg-emerald-50 p-4 text-sm leading-6 text-slate-700"><b className="text-emerald-800">Resposta do Codex</b><p className="mt-2 whitespace-pre-wrap">{proposal.response}</p></div>}{proposal.status === 'PROPOSAL_READY' && <button type="button" disabled={pending} onClick={onExecute} className="w-max rounded-lg bg-emerald-600 px-4 py-2 text-sm font-bold text-white hover:bg-emerald-700 disabled:opacity-50">{pending ? 'Enviando ao Runtime…' : 'Aprovar e executar no Codex'}</button>}</div>}
    {error && <p role="alert" className="mt-3 rounded-lg bg-red-50 p-3 text-sm text-red-700">{error}</p>}
  </section>;
}
