import type { ChatResponse } from '../../types/api';
import { Link } from 'react-router-dom';

export function ResponseCard({ response }: { response: ChatResponse }) {
  const metricEntries = Object.entries(response.metrics || {}).filter(([, value]) => ['string', 'number', 'boolean'].includes(typeof value)).slice(0, 4);
  return <div className="mt-4 grid gap-3">
    {response.rag && <div className="rounded-xl border border-violet-100 bg-violet-50 p-4 text-sm"><div className="font-bold text-violet-800">Contexto RAG</div><div className="mt-1 text-violet-700">{response.rag.retrieved ? `Contexto recuperado${response.rag.sources ? ` · ${response.rag.sources} fontes` : ''}.` : 'Nenhum contexto relevante recuperado.'}</div>{response.rag.query_id && <div className="mt-2 text-xs text-violet-500">Consulta: {response.rag.query_id}</div>}{response.rag.ranking_version && <div className="text-xs text-violet-500">Ranking: {response.rag.ranking_version}</div>}{response.rag.context_budget && <div className="text-xs text-violet-500">Orçamento de contexto: {response.rag.context_budget}</div>}{response.rag.data_quality && <div className="text-xs text-violet-500">Qualidade: {response.rag.data_quality}</div>}</div>}
    {response.plan && <div className="rounded-xl border border-blue-100 bg-blue-50 p-4 text-sm"><div className="font-bold text-blue-800">Plano de execução</div>{response.plan.title && <div className="mt-1 text-blue-700">{response.plan.title}</div>}{response.plan.steps?.length ? <ol className="mt-2 list-decimal pl-5 text-blue-700">{response.plan.steps.map((step) => <li key={step}>{step}</li>)}</ol> : <p className="mt-2 text-xs text-blue-600">Etapas ainda não informadas pelo Runtime.</p>}{response.plan.agents?.length ? <div className="mt-2 text-xs text-blue-600">Agents: {response.plan.agents.join(', ')}</div> : null}</div>}
    {metricEntries.length > 0 && <div className="rounded-xl border border-slate-200 bg-slate-50 p-4 text-sm"><div className="font-bold text-slate-700">Métricas observadas</div><div className="mt-3 grid grid-cols-2 gap-2">{metricEntries.map(([key, value]) => <div key={key}><span className="block text-[10px] uppercase tracking-wide text-slate-400">{key.replace(/_/g, ' ')}</span><strong className="text-slate-700">{String(value)}</strong></div>)}</div></div>}
    {response.run_id && <div className="rounded-xl border border-emerald-100 bg-emerald-50 p-4 text-sm"><div className="font-bold text-emerald-800">Execução iniciada</div><div className="mt-1 text-emerald-700">Acompanhe o run <code>{response.run_id}</code>.</div><Link className="mt-3 inline-flex rounded-lg bg-emerald-600 px-3 py-2 text-xs font-bold text-white hover:bg-emerald-700" to={`/tasks/${encodeURIComponent(response.run_id)}`}>Abrir execução</Link></div>}
  </div>;
}
