import { NavLink, useNavigate } from 'react-router-dom';
import type { Project } from '../../types/api';

const menu = [['⌂', 'Workspace', '/workspace'], ['▣', 'Tarefas', '/tasks'], ['◈', 'Agents', '/agents'], ['◇', 'Checkpoints', '/checkpoints'], ['⌕', 'RAG', '/rag'], ['≋', 'Logs', '/logs'], ['◈', 'Evidências', '/evidence'], ['◒', 'Modelos e custos', '/models'], ['⌘', 'Integrações', '/integrations'], ['⚙', 'Configurações', '/settings']] as const;
const navClass = ({ isActive }: { isActive: boolean }) => `group flex items-center gap-3 rounded-xl px-3 py-2.5 text-left text-sm transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-blue-500 ${isActive ? 'bg-blue-50 font-bold text-blue-600' : 'text-slate-500 hover:bg-slate-50 hover:text-blue-600'}`;
type Props = { projects: Project[]; projectId: string; collapsed: boolean; onToggle: () => void; onProjectChange: (id: string) => void };

export function WorkspaceSidebar({ projects, projectId, collapsed, onToggle, onProjectChange }: Props) {
  const navigate = useNavigate();
  return <aside className={`flex shrink-0 flex-col border-r border-slate-200 bg-white px-3 py-5 shadow-sm transition-all duration-200 ${collapsed ? 'w-[76px]' : 'w-[250px]'}`}><div className="flex items-center gap-2.5 px-2.5 pb-7"><span className="grid h-9 w-9 place-items-center rounded-xl bg-gradient-to-br from-blue-600 to-violet-600 font-extrabold text-white shadow-md">A</span>{!collapsed && <div><strong className="block text-lg">AGHUse Assistant</strong><small className="text-[11px] text-slate-400">Operações</small></div>}</div><label className="px-2.5 pb-1.5 text-[10px] font-bold tracking-wider text-slate-400">{!collapsed && 'PROJETO ATIVO'}</label><select className="mb-5 w-full rounded-lg border border-slate-200 bg-slate-50 px-2 py-2 text-sm text-slate-700 outline-none focus:ring-2 focus:ring-blue-500" aria-label="Projeto ativo" value={projectId} onChange={(event) => { onProjectChange(event.target.value); navigate('/workspace'); }}><option value="" disabled>Selecione</option>{projects.map((project) => <option key={project.project_id} value={project.project_id}>{project.name}</option>)}</select><nav className="grid gap-1" aria-label="Navegação principal">{menu.map(([icon, label, path]) => <NavLink className={navClass} title={label} key={label} to={path}><span className="w-5 text-center text-lg">{icon}</span>{!collapsed && label}</NavLink>)}</nav><div className="mt-5 rounded-xl border border-violet-100 bg-violet-50 px-3 py-3 text-xs text-violet-700">{collapsed ? '✦' : 'Escolha uma operação para começar.'}</div><button className="mt-auto rounded-lg px-3 py-2.5 text-left text-sm text-slate-400 transition hover:bg-slate-50 hover:text-blue-600 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-blue-500" onClick={onToggle}>{collapsed ? '»' : '« Recolher menu'}</button></aside>;
}
